# Generated by Django 5.2.2 on 2025-08-30 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RBACModelPermissionScope',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('included_fields', models.JSONField(blank=True, default=list)),
                ('excluded_fields', models.JSONField(blank=True, default=list)),
                (
                    'type',
                    models.CharField(
                        choices=[('base', 'Base'), ('extension', 'Extension')],
                        max_length=50,
                    ),
                ),
                ('group', models.CharField(blank=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='children',
                        to='account.rbacmodelpermissionscope',
                    ),
                ),
                (
                    'related_model',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
            ],
            options={
                'ordering': ['related_model', 'type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RBACPermission',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('create', 'Create'),
                            ('get', 'Get'),
                            ('update', 'Update'),
                            ('delete', 'Delete'),
                            ('export', 'Export'),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    'row_access',
                    models.CharField(
                        choices=[
                            ('all', 'All'),
                            ('profile_hierarchy', 'Profile Hierarchy'),
                            ('own', 'Own'),
                        ],
                        db_index=True,
                        default='all',
                        max_length=50,
                    ),
                ),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'scope',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rbac_permissions',
                        to='account.rbacmodelpermissionscope',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='RBACRole',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_staff_only', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'permissions',
                    models.ManyToManyField(
                        blank=True,
                        related_name='rbac_roles',
                        to='account.rbacpermission',
                    ),
                ),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'type',
                    models.CharField(
                        choices=[('tourist', 'Tourist'), ('real', 'Real')],
                        default='tourist',
                        max_length=50,
                    ),
                ),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.TextField(blank=True)),
                ('_national_id', models.TextField(blank=True, db_column='national_id')),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='member_profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'rbac_roles',
                    models.ManyToManyField(
                        blank=True,
                        related_name='member_profiles',
                        to='account.rbacrole',
                    ),
                ),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberRBACRole',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.rbacrole',),
        ),
        migrations.CreateModel(
            name='StaffRBACRole',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.rbacrole',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'type',
                    models.CharField(
                        choices=[('staff', 'Staff'), ('admin', 'Admin')],
                        default='staff',
                        max_length=50,
                    ),
                ),
                (
                    'rbac_roles',
                    models.ManyToManyField(
                        blank=True, related_name='staff_profiles', to='account.rbacrole'
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='staff_profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='rbacmodelpermissionscope',
            index=models.Index(fields=['code'], name='account_rba_code_9a185e_idx'),
        ),
        migrations.AddIndex(
            model_name='rbacmodelpermissionscope',
            index=models.Index(
                fields=['related_model', 'name'], name='account_rba_related_d51311_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='rbacmodelpermissionscope',
            index=models.Index(
                fields=['parent'], name='account_rba_parent__bef20a_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='rbacmodelpermissionscope',
            index=models.Index(fields=['type'], name='account_rba_type_101e81_idx'),
        ),
        migrations.AddIndex(
            model_name='rbacmodelpermissionscope',
            index=models.Index(fields=['group'], name='account_rba_group_38f77d_idx'),
        ),
        migrations.AddIndex(
            model_name='rbacmodelpermissionscope',
            index=models.Index(
                fields=['is_active'], name='account_rba_is_acti_9dac0a_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='rbacpermission',
            index=models.Index(
                fields=['scope', 'action'], name='account_rba_scope_i_49c3fa_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='rbacpermission',
            index=models.Index(
                fields=['row_access'], name='account_rba_row_acc_772c37_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='rbacpermission',
            unique_together={('scope', 'action', 'row_access')},
        ),
    ]
