# Generated by Django 5.2.2 on 2025-09-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rbacmodelpermissionscope',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rbacpermission',
            name='action',
            field=models.CharField(
                choices=[
                    ('create', 'Create'),
                    ('get', 'Get'),
                    ('update', 'Update'),
                    ('delete', 'Delete'),
                    ('export', 'Export'),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='rbacpermission',
            name='row_access',
            field=models.CharField(
                choices=[
                    ('all', 'All'),
                    ('profile_hierarchy', 'Profile Hierarchy'),
                    ('own', 'Own'),
                ],
                default='all',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='rbacpermission',
            index=models.Index(fields=['action'], name='account_rba_action_9f7ce7_idx'),
        ),
    ]
