# Generated by Django 5.2.2 on 2025-09-07 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('account', '0002_alter_member_is_active_and_more'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeInfo',
            fields=[
                (
                    'bike_id',
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ('bike_name', models.CharField(max_length=100)),
                ('bike_model', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'telemetry_device',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='bike',
                        to='telemetry.telemetrydevice',
                    ),
                ),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BikeCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [
                    models.Index(
                        fields=['category_name'], name='bike_bikeca_categor_8d6cf0_idx'
                    ),
                    models.Index(
                        fields=['is_active'], name='bike_bikeca_is_acti_001da9_idx'
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='BikeErrorLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.CharField(max_length=50)),
                (
                    'level',
                    models.CharField(
                        choices=[
                            ('info', 'Info'),
                            ('warning', 'Warning'),
                            ('critical', 'Critical'),
                        ],
                        default='warning',
                        max_length=20,
                    ),
                ),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('telemetry_record_snapshot', models.JSONField(blank=True, null=True)),
                ('extra_context', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'telemetry_device',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='bike_error_logs',
                        to='telemetry.telemetrydevice',
                    ),
                ),
                (
                    'bike',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='bike_error_logs',
                        to='bike.bikeinfo',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BikeSeries',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('series_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='bike_series',
                        to='bike.bikecategory',
                    ),
                ),
            ],
            options={
                'ordering': ['category', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='bikeinfo',
            name='series',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bikes',
                to='bike.bikeseries',
            ),
        ),
        migrations.CreateModel(
            name='BikeErrorLogStatus',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                (
                    'error_log',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='read_statuses',
                        to='bike.bikeerrorlog',
                    ),
                ),
                (
                    'staff',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='bike_error_read_statuses',
                        to='account.staff',
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['staff', 'is_read'],
                        name='bike_bikeer_staff_i_7d4a89_idx',
                    ),
                    models.Index(
                        fields=['error_log', 'staff'],
                        name='bike_bikeer_error_l_ff412a_idx',
                    ),
                ],
                'unique_together': {('error_log', 'staff')},
            },
        ),
        migrations.CreateModel(
            name='BikeRealtimeStatus',
            fields=[
                (
                    'bike',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='realtime_status',
                        serialize=False,
                        to='bike.bikeinfo',
                    ),
                ),
                ('latitude', models.IntegerField(verbose_name='緯度 * 10^6')),
                ('longitude', models.IntegerField(verbose_name='經度 * 10^6')),
                ('battery_level', models.SmallIntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('idle', 'Idle'),
                            ('rented', 'Rented'),
                            ('maintenance', 'Maintenance'),
                            ('error', 'Error'),
                        ],
                        default='idle',
                        max_length=50,
                    ),
                ),
                (
                    'orig_status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('idle', 'Idle'),
                            ('rented', 'Rented'),
                            ('maintenance', 'Maintenance'),
                            ('error', 'Error'),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ('current_member_ids', models.JSONField(blank=True, default=list)),
                ('last_seen', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['status'], name='bike_bikere_status_25c264_idx'
                    ),
                    models.Index(
                        fields=['last_seen'], name='bike_bikere_last_se_da582e_idx'
                    ),
                    models.Index(
                        fields=['latitude', 'longitude'],
                        name='bike_bikere_latitud_2346da_idx',
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name='bikeerrorlog',
            index=models.Index(
                fields=['bike', 'level'], name='bike_bikeer_bike_id_ec03fd_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='bikeerrorlog',
            index=models.Index(
                fields=['created_at'], name='bike_bikeer_created_5f6337_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='bikeerrorlog',
            index=models.Index(fields=['level'], name='bike_bikeer_level_e624bf_idx'),
        ),
        migrations.AddIndex(
            model_name='bikeerrorlog',
            index=models.Index(
                fields=['telemetry_device'], name='bike_bikeer_telemet_d4d65b_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='bikeseries',
            index=models.Index(
                fields=['series_name'], name='bike_bikese_series__195005_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='bikeseries',
            index=models.Index(
                fields=['is_active'], name='bike_bikese_is_acti_da4aa4_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='bikeseries',
            unique_together={('category', 'series_name')},
        ),
        migrations.AddIndex(
            model_name='bikeinfo',
            index=models.Index(
                fields=['series'], name='bike_bikein_series__d14f08_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='bikeinfo',
            index=models.Index(
                fields=['is_active'], name='bike_bikein_is_acti_2354b0_idx'
            ),
        ),
    ]
