# Generated by Django 5.2.2 on 2025-09-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikerealtimestatus',
            old_name='battery_level',
            new_name='soc',
        ),
        migrations.AddField(
            model_name='bikerealtimestatus',
            name='vehicle_speed',
            field=models.SmallIntegerField(default=30),
            preserve_default=False,
        ),
    ]
