# Generated by Django 5.2.2 on 2025-09-11 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0002_alter_member_is_active_and_more'),
        ('bike', '0002_rename_battery_level_bikerealtimestatus_soc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikerealtimestatus',
            name='current_member_ids',
        ),
        migrations.AddField(
            model_name='bikerealtimestatus',
            name='current_member',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='bike_realtime_status',
                to='account.member',
            ),
        ),
    ]
