# Generated by Django 5.2.2 on 2025-09-13 03:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bike', '0003_remove_bikerealtimestatus_current_member_ids_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bikeseries',
            name='bike_bikese_is_acti_da4aa4_idx',
        ),
        migrations.RemoveField(
            model_name='bikeseries',
            name='is_active',
        ),
    ]
