# Generated by Django 5.2.2 on 2025-09-13 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bike', '0004_remove_bikeseries_bike_bikese_is_acti_da4aa4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bikeinfo',
            name='bike_bikein_is_acti_2354b0_idx',
        ),
        migrations.RemoveField(
            model_name='bikeinfo',
            name='is_active',
        ),
    ]
