# Generated by Django 5.2.2 on 2025-09-13 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bike', '0005_remove_bikeinfo_bike_bikein_is_acti_2354b0_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bikecategory',
            name='bike_bikeca_is_acti_001da9_idx',
        ),
        migrations.RemoveField(
            model_name='bikecategory',
            name='is_active',
        ),
    ]
