# Generated by Django 5.2.2 on 2025-09-13 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bike', '0006_remove_bikecategory_bike_bikeca_is_acti_001da9_idx_and_more'),
        (
            'telemetry',
            '0002_remove_telemetrydevice_telemetry_t_is_acti_5cd141_idx_and_more',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeerrorlog',
            name='extra_context',
        ),
        migrations.RemoveField(
            model_name='bikeerrorlog',
            name='telemetry_record_snapshot',
        ),
        migrations.AddField(
            model_name='bikeerrorlog',
            name='telemetry_record',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='error_logs',
                to='telemetry.telemetryrecord',
            ),
        ),
        migrations.AddIndex(
            model_name='bikeerrorlog',
            index=models.Index(
                fields=['telemetry_record'], name='bike_bikeer_telemet_64b4cc_idx'
            ),
        ),
    ]
