services:
  koala-db:
    image: postgres:14
    restart: on-failure
    env_file:
      - ./env/koala-local.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - koala-network
    ports:
      - "5432:5432"

  koala-redis:
    restart: on-failure
    image: redis:7.4.2
    env_file:
      - ./env/koala-local.env
    volumes:
      - redis-data:/data
    networks:
      - koala-network
    ports:
      - "6379:6379"

  koala:
    build: .
    depends_on:
      - koala-db
      - koala-redis
      - koala-rabbitmq
    restart: on-failure
    env_file:
      - ./env/koala-local.env
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    networks:
      - koala-network
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py migrate &&
              python manage.py register_periodic_tasks &&
              python manage.py runserver 0.0.0.0:8000"

  koala-rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    env_file:
      - ./env/koala-local.env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - koala-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  # koala-celery-playlog:
  #   build: .
  #   depends_on:
  #     - koala-db
  #     - koala-redis
  #     - koala-rabbitmq
  #   restart: on-failure
  #   env_file:
  #     - ./env/koala-local.env
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./:/usr/src/app
  #   networks:
  #     - koala-network
  #   healthcheck:
  #     test: ["CMD", "celery", "-A", "koala", "status"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 30s
  #   entrypoint: ["/usr/src/app/entrypoint-celery.sh", "playlog_q"]

  # koala-celery-token:
  #   build: .
  #   depends_on:
  #     - koala-db
  #     - koala-redis
  #     - koala-rabbitmq
  #   restart: on-failure
  #   env_file:
  #     - ./env/koala-local.env
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./:/usr/src/app
  #   networks:
  #     - koala-network
  #   healthcheck:
  #     test: ["CMD", "celery", "-A", "koala", "status"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 30s
  #   entrypoint: ["/usr/src/app/entrypoint-celery.sh", "refresh_spotify_access_token_q"]

  koala-celery-beat:
    build: .
    restart: on-failure
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./env/koala-local.env
    depends_on:
      - koala-db
      - koala-redis
      - koala-rabbitmq
    networks:
      - koala-network
    healthcheck:
      test: ["CMD", "pgrep", "-f", "celery beat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: celery -A koala beat --loglevel=info

networks:
  koala-network:
    driver: bridge

volumes:
  db_data:
  redis-data:
  rabbitmq-data:
