# Generated by Django 5.2.2 on 2025-09-07 08:30

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('account', '0002_alter_member_is_active_and_more'),
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeRental',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                (
                    'rental_status',
                    models.CharField(
                        choices=[
                            ('reserved', 'Reserved'),
                            ('active', 'Active'),
                            ('completed', 'Completed'),
                            ('cancelled', 'Cancelled'),
                        ],
                        default='active',
                        max_length=20,
                    ),
                ),
                (
                    'pickup_location',
                    models.CharField(blank=True, default='', max_length=200),
                ),
                (
                    'return_location',
                    models.CharField(blank=True, default='', max_length=200),
                ),
                (
                    'total_fee',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=10
                    ),
                ),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'bike',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rentals',
                        to='bike.bikeinfo',
                    ),
                ),
                (
                    'member',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='bike_rentals',
                        to='account.member',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['member', 'start_time'],
                        name='rental_bike_member__f3a9ce_idx',
                    ),
                    models.Index(
                        fields=['bike', 'start_time'],
                        name='rental_bike_bike_id_a2b84e_idx',
                    ),
                    models.Index(
                        fields=['rental_status'], name='rental_bike_rental__56fb00_idx'
                    ),
                    models.Index(
                        fields=['start_time'], name='rental_bike_start_t_90eb3d_idx'
                    ),
                    models.Index(
                        fields=['end_time'], name='rental_bike_end_tim_9d270a_idx'
                    ),
                    models.Index(
                        fields=['created_at'], name='rental_bike_created_b261f1_idx'
                    ),
                ],
            },
        ),
    ]
