# Generated by Django 5.2.2 on 2025-09-07 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('account', '0002_alter_member_is_active_and_more'),
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOverviewStatistics',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('online_bikes_count', models.IntegerField(default=0)),
                ('offline_bikes_count', models.IntegerField(default=0)),
                ('total_distance_km', models.FloatField(default=0.0)),
                ('carbon_reduction_kg', models.FloatField(default=0.0)),
                ('average_soc', models.FloatField(blank=True, null=True)),
                ('collected_time', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-collected_time'],
                'indexes': [
                    models.Index(
                        fields=['collected_time'], name='statistic_d_collect_1edd2a_idx'
                    ),
                    models.Index(
                        fields=['created_at'], name='statistic_d_created_a61896_idx'
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='HourlyOverviewStatistics',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('online_bikes_count', models.IntegerField(default=0)),
                ('offline_bikes_count', models.IntegerField(default=0)),
                ('average_soc', models.FloatField(blank=True, null=True)),
                ('collected_time', models.DateTimeField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-collected_time'],
                'indexes': [
                    models.Index(
                        fields=['collected_time'], name='statistic_h_collect_869d78_idx'
                    ),
                    models.Index(
                        fields=['created_at'], name='statistic_h_created_e1b085_idx'
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='LocationStatistics',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('latitude', models.IntegerField(verbose_name='緯度 * 10^6')),
                ('longitude', models.IntegerField(verbose_name='經度 * 10^6')),
                ('record_count', models.IntegerField(default=1)),
                ('record_time', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'bike',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='location_statistics',
                        to='bike.bikeinfo',
                    ),
                ),
                (
                    'member',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='location_statistics',
                        to='account.member',
                    ),
                ),
            ],
            options={
                'ordering': ['-record_time'],
                'indexes': [
                    models.Index(
                        fields=['bike', 'record_time'],
                        name='statistic_l_bike_id_c9186c_idx',
                    ),
                    models.Index(
                        fields=['member', 'record_time'],
                        name='statistic_l_member__81520a_idx',
                    ),
                    models.Index(
                        fields=['latitude', 'longitude'],
                        name='statistic_l_latitud_da7e96_idx',
                    ),
                    models.Index(
                        fields=['record_time'], name='statistic_l_record__c4f23b_idx'
                    ),
                    models.Index(
                        fields=['record_count'], name='statistic_l_record__f01d4c_idx'
                    ),
                ],
                'unique_together': {
                    ('bike', 'member', 'latitude', 'longitude', 'record_time')
                },
            },
        ),
    ]
