# Generated by Django 5.2.2 on 2025-09-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyoverviewstatistics',
            name='carbon_reduction_kg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hourlyoverviewstatistics',
            name='distance_km',
            field=models.FloatField(default=0.0),
        ),
    ]
