# Generated by Django 4.2.13 on 2025-09-21 16:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('statistic', '0003_geometrycoordinate_ridesession_routematchresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGeometryCoordinateStatistics',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('collected_time', models.DateField()),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-collected_time', '-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='HourlyGeometryCoordinateStatistics',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('collected_time', models.DateTimeField()),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-collected_time', '-usage_count'],
            },
        ),
        migrations.AlterModelOptions(
            name='geometrycoordinate',
            options={'ordering': ['-total_usage_count', '-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='geometrycoordinate',
            name='statistic_g_usage_c_72b622_idx',
        ),
        migrations.AlterUniqueTogether(
            name='geometrycoordinate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='geometrycoordinate',
            name='total_usage_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='routematchresult',
            name='resync_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geometrycoordinate',
            name='is_mock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='geometrycoordinate',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='geometrycoordinate',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='geometrycoordinate',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='routematchresult',
            name='average_confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='routematchresult',
            name='distance_meters',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='routematchresult',
            name='end_point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='routematchresult',
            name='fallback_strategy',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='routematchresult',
            name='geometry',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326),
        ),
        migrations.AlterField(
            model_name='routematchresult',
            name='is_sync_geometry_coordinate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='routematchresult',
            name='start_point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterUniqueTogether(
            name='geometrycoordinate',
            unique_together={('latitude', 'longitude')},
        ),
        migrations.AddIndex(
            model_name='geometrycoordinate',
            index=models.Index(
                fields=['total_usage_count'], name='statistic_g_total_u_7ec725_idx'
            ),
        ),
        migrations.AddField(
            model_name='hourlygeometrycoordinatestatistics',
            name='geometry_coordinate',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='hourly_stats',
                to='statistic.geometrycoordinate',
            ),
        ),
        migrations.AddField(
            model_name='dailygeometrycoordinatestatistics',
            name='geometry_coordinate',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='daily_stats',
                to='statistic.geometrycoordinate',
            ),
        ),
        migrations.RemoveField(
            model_name='geometrycoordinate',
            name='usage_count',
        ),
        migrations.AddIndex(
            model_name='hourlygeometrycoordinatestatistics',
            index=models.Index(
                fields=['collected_time'], name='statistic_h_collect_06eb33_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='hourlygeometrycoordinatestatistics',
            index=models.Index(
                fields=['geometry_coordinate', 'collected_time'],
                name='statistic_h_geometr_70114c_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='hourlygeometrycoordinatestatistics',
            index=models.Index(
                fields=['usage_count'], name='statistic_h_usage_c_36805d_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='hourlygeometrycoordinatestatistics',
            unique_together={('geometry_coordinate', 'collected_time')},
        ),
        migrations.AddIndex(
            model_name='dailygeometrycoordinatestatistics',
            index=models.Index(
                fields=['collected_time'], name='statistic_d_collect_25d35e_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='dailygeometrycoordinatestatistics',
            index=models.Index(
                fields=['geometry_coordinate', 'collected_time'],
                name='statistic_d_geometr_b6736e_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='dailygeometrycoordinatestatistics',
            index=models.Index(
                fields=['usage_count'], name='statistic_d_usage_c_e95be2_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='dailygeometrycoordinatestatistics',
            unique_together={('geometry_coordinate', 'collected_time')},
        ),
    ]
