# Generated by Django 5.2.2 on 2025-09-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telemetrydevice',
            name='telemetry_t_is_acti_5cd141_idx',
        ),
        migrations.RemoveField(
            model_name='telemetrydevice',
            name='is_active',
        ),
        migrations.AddField(
            model_name='telemetrydevice',
            name='status',
            field=models.CharField(
                choices=[
                    ('available', 'Available'),
                    ('deployed', 'Deployed'),
                    ('maintenance', 'Maintenance'),
                ],
                default='available',
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name='telemetrydevice',
            index=models.Index(fields=['status'], name='telemetry_t_status_6849e3_idx'),
        ),
    ]
